/*
EZPin Access API V2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ezpin

import (
	"encoding/json"
)

// checks if the OrdersPost400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrdersPost400Response{}

// OrdersPost400Response struct for OrdersPost400Response
type OrdersPost400Response struct {
	// detail of returned response
	Detail *string `json:"detail,omitempty"`
	// error code
	Code *int32 `json:"code,omitempty"`
}

// NewOrdersPost400Response instantiates a new OrdersPost400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrdersPost400Response() *OrdersPost400Response {
	this := OrdersPost400Response{}
	return &this
}

// NewOrdersPost400ResponseWithDefaults instantiates a new OrdersPost400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrdersPost400ResponseWithDefaults() *OrdersPost400Response {
	this := OrdersPost400Response{}
	return &this
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *OrdersPost400Response) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersPost400Response) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *OrdersPost400Response) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *OrdersPost400Response) SetDetail(v string) {
	o.Detail = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *OrdersPost400Response) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersPost400Response) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *OrdersPost400Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *OrdersPost400Response) SetCode(v int32) {
	o.Code = &v
}

func (o OrdersPost400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrdersPost400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	return toSerialize, nil
}

type NullableOrdersPost400Response struct {
	value *OrdersPost400Response
	isSet bool
}

func (v NullableOrdersPost400Response) Get() *OrdersPost400Response {
	return v.value
}

func (v *NullableOrdersPost400Response) Set(val *OrdersPost400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableOrdersPost400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableOrdersPost400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrdersPost400Response(val *OrdersPost400Response) *NullableOrdersPost400Response {
	return &NullableOrdersPost400Response{value: val, isSet: true}
}

func (v NullableOrdersPost400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrdersPost400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


