/*
EZPin Access API V2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ezpin

import (
	"encoding/json"
)

// checks if the ShowingCurrency type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShowingCurrency{}

// ShowingCurrency struct for ShowingCurrency
type ShowingCurrency struct {
	// name of showing currency
	Currency *string `json:"currency,omitempty"`
	// symbol of showing currency
	Symbol *string `json:"symbol,omitempty"`
	// code of showing currency
	Code *string `json:"code,omitempty"`
}

// NewShowingCurrency instantiates a new ShowingCurrency object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShowingCurrency() *ShowingCurrency {
	this := ShowingCurrency{}
	return &this
}

// NewShowingCurrencyWithDefaults instantiates a new ShowingCurrency object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShowingCurrencyWithDefaults() *ShowingCurrency {
	this := ShowingCurrency{}
	return &this
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ShowingCurrency) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShowingCurrency) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ShowingCurrency) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *ShowingCurrency) SetCurrency(v string) {
	o.Currency = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *ShowingCurrency) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShowingCurrency) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *ShowingCurrency) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *ShowingCurrency) SetSymbol(v string) {
	o.Symbol = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ShowingCurrency) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShowingCurrency) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ShowingCurrency) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ShowingCurrency) SetCode(v string) {
	o.Code = &v
}

func (o ShowingCurrency) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShowingCurrency) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	return toSerialize, nil
}

type NullableShowingCurrency struct {
	value *ShowingCurrency
	isSet bool
}

func (v NullableShowingCurrency) Get() *ShowingCurrency {
	return v.value
}

func (v *NullableShowingCurrency) Set(val *ShowingCurrency) {
	v.value = val
	v.isSet = true
}

func (v NullableShowingCurrency) IsSet() bool {
	return v.isSet
}

func (v *NullableShowingCurrency) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShowingCurrency(val *ShowingCurrency) *NullableShowingCurrency {
	return &NullableShowingCurrency{value: val, isSet: true}
}

func (v NullableShowingCurrency) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShowingCurrency) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


