/*
EZPin Access API V2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ezpin

import (
	"encoding/json"
)

// checks if the OrdersGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrdersGet200Response{}

// OrdersGet200Response struct for OrdersGet200Response
type OrdersGet200Response struct {
	// Number of total orders
	Count *float32 `json:"count,omitempty"`
	// next page of order list
	Next *string `json:"next,omitempty"`
	// previous page of order list
	Previous *string `json:"previous,omitempty"`
	Results []Order `json:"results,omitempty"`
}

// NewOrdersGet200Response instantiates a new OrdersGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrdersGet200Response() *OrdersGet200Response {
	this := OrdersGet200Response{}
	return &this
}

// NewOrdersGet200ResponseWithDefaults instantiates a new OrdersGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrdersGet200ResponseWithDefaults() *OrdersGet200Response {
	this := OrdersGet200Response{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *OrdersGet200Response) GetCount() float32 {
	if o == nil || IsNil(o.Count) {
		var ret float32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersGet200Response) GetCountOk() (*float32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *OrdersGet200Response) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given float32 and assigns it to the Count field.
func (o *OrdersGet200Response) SetCount(v float32) {
	o.Count = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *OrdersGet200Response) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersGet200Response) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *OrdersGet200Response) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *OrdersGet200Response) SetNext(v string) {
	o.Next = &v
}

// GetPrevious returns the Previous field value if set, zero value otherwise.
func (o *OrdersGet200Response) GetPrevious() string {
	if o == nil || IsNil(o.Previous) {
		var ret string
		return ret
	}
	return *o.Previous
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersGet200Response) GetPreviousOk() (*string, bool) {
	if o == nil || IsNil(o.Previous) {
		return nil, false
	}
	return o.Previous, true
}

// HasPrevious returns a boolean if a field has been set.
func (o *OrdersGet200Response) HasPrevious() bool {
	if o != nil && !IsNil(o.Previous) {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given string and assigns it to the Previous field.
func (o *OrdersGet200Response) SetPrevious(v string) {
	o.Previous = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *OrdersGet200Response) GetResults() []Order {
	if o == nil || IsNil(o.Results) {
		var ret []Order
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersGet200Response) GetResultsOk() ([]Order, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *OrdersGet200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []Order and assigns it to the Results field.
func (o *OrdersGet200Response) SetResults(v []Order) {
	o.Results = v
}

func (o OrdersGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrdersGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Previous) {
		toSerialize["previous"] = o.Previous
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableOrdersGet200Response struct {
	value *OrdersGet200Response
	isSet bool
}

func (v NullableOrdersGet200Response) Get() *OrdersGet200Response {
	return v.value
}

func (v *NullableOrdersGet200Response) Set(val *OrdersGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableOrdersGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableOrdersGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrdersGet200Response(val *OrdersGet200Response) *NullableOrdersGet200Response {
	return &NullableOrdersGet200Response{value: val, isSet: true}
}

func (v NullableOrdersGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrdersGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


