/*
EZPin Access API V2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ezpin

import (
	"encoding/json"
)

// checks if the CatalogsProductSkuAvailabilityGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatalogsProductSkuAvailabilityGet200Response{}

// CatalogsProductSkuAvailabilityGet200Response struct for CatalogsProductSkuAvailabilityGet200Response
type CatalogsProductSkuAvailabilityGet200Response struct {
	// Availability status
	Availability *bool `json:"availability,omitempty"`
	// Detailed information
	Detail *string `json:"detail,omitempty"`
}

// NewCatalogsProductSkuAvailabilityGet200Response instantiates a new CatalogsProductSkuAvailabilityGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogsProductSkuAvailabilityGet200Response() *CatalogsProductSkuAvailabilityGet200Response {
	this := CatalogsProductSkuAvailabilityGet200Response{}
	return &this
}

// NewCatalogsProductSkuAvailabilityGet200ResponseWithDefaults instantiates a new CatalogsProductSkuAvailabilityGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogsProductSkuAvailabilityGet200ResponseWithDefaults() *CatalogsProductSkuAvailabilityGet200Response {
	this := CatalogsProductSkuAvailabilityGet200Response{}
	return &this
}

// GetAvailability returns the Availability field value if set, zero value otherwise.
func (o *CatalogsProductSkuAvailabilityGet200Response) GetAvailability() bool {
	if o == nil || IsNil(o.Availability) {
		var ret bool
		return ret
	}
	return *o.Availability
}

// GetAvailabilityOk returns a tuple with the Availability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogsProductSkuAvailabilityGet200Response) GetAvailabilityOk() (*bool, bool) {
	if o == nil || IsNil(o.Availability) {
		return nil, false
	}
	return o.Availability, true
}

// HasAvailability returns a boolean if a field has been set.
func (o *CatalogsProductSkuAvailabilityGet200Response) HasAvailability() bool {
	if o != nil && !IsNil(o.Availability) {
		return true
	}

	return false
}

// SetAvailability gets a reference to the given bool and assigns it to the Availability field.
func (o *CatalogsProductSkuAvailabilityGet200Response) SetAvailability(v bool) {
	o.Availability = &v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *CatalogsProductSkuAvailabilityGet200Response) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogsProductSkuAvailabilityGet200Response) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *CatalogsProductSkuAvailabilityGet200Response) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *CatalogsProductSkuAvailabilityGet200Response) SetDetail(v string) {
	o.Detail = &v
}

func (o CatalogsProductSkuAvailabilityGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatalogsProductSkuAvailabilityGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Availability) {
		toSerialize["availability"] = o.Availability
	}
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	return toSerialize, nil
}

type NullableCatalogsProductSkuAvailabilityGet200Response struct {
	value *CatalogsProductSkuAvailabilityGet200Response
	isSet bool
}

func (v NullableCatalogsProductSkuAvailabilityGet200Response) Get() *CatalogsProductSkuAvailabilityGet200Response {
	return v.value
}

func (v *NullableCatalogsProductSkuAvailabilityGet200Response) Set(val *CatalogsProductSkuAvailabilityGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogsProductSkuAvailabilityGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogsProductSkuAvailabilityGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogsProductSkuAvailabilityGet200Response(val *CatalogsProductSkuAvailabilityGet200Response) *NullableCatalogsProductSkuAvailabilityGet200Response {
	return &NullableCatalogsProductSkuAvailabilityGet200Response{value: val, isSet: true}
}

func (v NullableCatalogsProductSkuAvailabilityGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogsProductSkuAvailabilityGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


