/*
EZPin Access API V2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ezpin

import (
	"encoding/json"
)

// checks if the CryptoCurrencyOrderCryptoCurrencyData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CryptoCurrencyOrderCryptoCurrencyData{}

// CryptoCurrencyOrderCryptoCurrencyData struct for CryptoCurrencyOrderCryptoCurrencyData
type CryptoCurrencyOrderCryptoCurrencyData struct {
	// crypto currency title
	Title *string `json:"title,omitempty"`
	// code of this cryptocurreny
	Code *string `json:"code,omitempty"`
	// symbol of this crypto currency
	Symbol *string `json:"symbol,omitempty"`
}

// NewCryptoCurrencyOrderCryptoCurrencyData instantiates a new CryptoCurrencyOrderCryptoCurrencyData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCryptoCurrencyOrderCryptoCurrencyData() *CryptoCurrencyOrderCryptoCurrencyData {
	this := CryptoCurrencyOrderCryptoCurrencyData{}
	return &this
}

// NewCryptoCurrencyOrderCryptoCurrencyDataWithDefaults instantiates a new CryptoCurrencyOrderCryptoCurrencyData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCryptoCurrencyOrderCryptoCurrencyDataWithDefaults() *CryptoCurrencyOrderCryptoCurrencyData {
	this := CryptoCurrencyOrderCryptoCurrencyData{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CryptoCurrencyOrderCryptoCurrencyData) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrencyOrderCryptoCurrencyData) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CryptoCurrencyOrderCryptoCurrencyData) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CryptoCurrencyOrderCryptoCurrencyData) SetTitle(v string) {
	o.Title = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CryptoCurrencyOrderCryptoCurrencyData) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrencyOrderCryptoCurrencyData) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CryptoCurrencyOrderCryptoCurrencyData) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *CryptoCurrencyOrderCryptoCurrencyData) SetCode(v string) {
	o.Code = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *CryptoCurrencyOrderCryptoCurrencyData) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CryptoCurrencyOrderCryptoCurrencyData) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *CryptoCurrencyOrderCryptoCurrencyData) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *CryptoCurrencyOrderCryptoCurrencyData) SetSymbol(v string) {
	o.Symbol = &v
}

func (o CryptoCurrencyOrderCryptoCurrencyData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CryptoCurrencyOrderCryptoCurrencyData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	return toSerialize, nil
}

type NullableCryptoCurrencyOrderCryptoCurrencyData struct {
	value *CryptoCurrencyOrderCryptoCurrencyData
	isSet bool
}

func (v NullableCryptoCurrencyOrderCryptoCurrencyData) Get() *CryptoCurrencyOrderCryptoCurrencyData {
	return v.value
}

func (v *NullableCryptoCurrencyOrderCryptoCurrencyData) Set(val *CryptoCurrencyOrderCryptoCurrencyData) {
	v.value = val
	v.isSet = true
}

func (v NullableCryptoCurrencyOrderCryptoCurrencyData) IsSet() bool {
	return v.isSet
}

func (v *NullableCryptoCurrencyOrderCryptoCurrencyData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCryptoCurrencyOrderCryptoCurrencyData(val *CryptoCurrencyOrderCryptoCurrencyData) *NullableCryptoCurrencyOrderCryptoCurrencyData {
	return &NullableCryptoCurrencyOrderCryptoCurrencyData{value: val, isSet: true}
}

func (v NullableCryptoCurrencyOrderCryptoCurrencyData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCryptoCurrencyOrderCryptoCurrencyData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


