/*
EZPin Access API V2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ezpin

import (
	"encoding/json"
)

// checks if the OrdersReferenceCodeCardsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrdersReferenceCodeCardsGet200Response{}

// OrdersReferenceCodeCardsGet200Response struct for OrdersReferenceCodeCardsGet200Response
type OrdersReferenceCodeCardsGet200Response struct {
	Results []Card `json:"results,omitempty"`
}

// NewOrdersReferenceCodeCardsGet200Response instantiates a new OrdersReferenceCodeCardsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrdersReferenceCodeCardsGet200Response() *OrdersReferenceCodeCardsGet200Response {
	this := OrdersReferenceCodeCardsGet200Response{}
	return &this
}

// NewOrdersReferenceCodeCardsGet200ResponseWithDefaults instantiates a new OrdersReferenceCodeCardsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrdersReferenceCodeCardsGet200ResponseWithDefaults() *OrdersReferenceCodeCardsGet200Response {
	this := OrdersReferenceCodeCardsGet200Response{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *OrdersReferenceCodeCardsGet200Response) GetResults() []Card {
	if o == nil || IsNil(o.Results) {
		var ret []Card
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersReferenceCodeCardsGet200Response) GetResultsOk() ([]Card, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *OrdersReferenceCodeCardsGet200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []Card and assigns it to the Results field.
func (o *OrdersReferenceCodeCardsGet200Response) SetResults(v []Card) {
	o.Results = v
}

func (o OrdersReferenceCodeCardsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrdersReferenceCodeCardsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableOrdersReferenceCodeCardsGet200Response struct {
	value *OrdersReferenceCodeCardsGet200Response
	isSet bool
}

func (v NullableOrdersReferenceCodeCardsGet200Response) Get() *OrdersReferenceCodeCardsGet200Response {
	return v.value
}

func (v *NullableOrdersReferenceCodeCardsGet200Response) Set(val *OrdersReferenceCodeCardsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableOrdersReferenceCodeCardsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableOrdersReferenceCodeCardsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrdersReferenceCodeCardsGet200Response(val *OrdersReferenceCodeCardsGet200Response) *NullableOrdersReferenceCodeCardsGet200Response {
	return &NullableOrdersReferenceCodeCardsGet200Response{value: val, isSet: true}
}

func (v NullableOrdersReferenceCodeCardsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrdersReferenceCodeCardsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


