/*
EZPin Access API V2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ezpin

import (
	"encoding/json"
)

// checks if the OrdersPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrdersPostRequest{}

// OrdersPostRequest struct for OrdersPostRequest
type OrdersPostRequest struct {
	// Catalog SKU
	Sku *float32 `json:"sku,omitempty"`
	// Item count
	Quantity *float32 `json:"quantity,omitempty"`
	// To determine whether you want to pre order your request or not. The product must support pre order mood. if you pass true your cards will get ready in the future.
	PreOder *bool `json:"pre_oder,omitempty"`
	// Item price
	Price *float32 `json:"price,omitempty"`
	// 0-None 1-E-mail 2-SMS 3-WhatsApp
	DeliveryType *float32 `json:"delivery_type,omitempty"`
	// E-mail or Phone/Whatsapp number you want the order to be delivered to.
	Destination *string `json:"destination,omitempty"`
	// Terminal ID of the sub-users that can be defined in setting section in user panel
	TerminalId *float32 `json:"terminal_id,omitempty"`
	// Pin defined for sub-user
	TerminalPin *float32 `json:"terminal_pin,omitempty"`
	// Refernce code. A unique UUID V4 referece code must be included in request
	ReferenceCode *string `json:"reference_code,omitempty"`
}

// NewOrdersPostRequest instantiates a new OrdersPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrdersPostRequest() *OrdersPostRequest {
	this := OrdersPostRequest{}
	return &this
}

// NewOrdersPostRequestWithDefaults instantiates a new OrdersPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrdersPostRequestWithDefaults() *OrdersPostRequest {
	this := OrdersPostRequest{}
	return &this
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *OrdersPostRequest) GetSku() float32 {
	if o == nil || IsNil(o.Sku) {
		var ret float32
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersPostRequest) GetSkuOk() (*float32, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *OrdersPostRequest) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given float32 and assigns it to the Sku field.
func (o *OrdersPostRequest) SetSku(v float32) {
	o.Sku = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *OrdersPostRequest) GetQuantity() float32 {
	if o == nil || IsNil(o.Quantity) {
		var ret float32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersPostRequest) GetQuantityOk() (*float32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *OrdersPostRequest) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float32 and assigns it to the Quantity field.
func (o *OrdersPostRequest) SetQuantity(v float32) {
	o.Quantity = &v
}

// GetPreOder returns the PreOder field value if set, zero value otherwise.
func (o *OrdersPostRequest) GetPreOder() bool {
	if o == nil || IsNil(o.PreOder) {
		var ret bool
		return ret
	}
	return *o.PreOder
}

// GetPreOderOk returns a tuple with the PreOder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersPostRequest) GetPreOderOk() (*bool, bool) {
	if o == nil || IsNil(o.PreOder) {
		return nil, false
	}
	return o.PreOder, true
}

// HasPreOder returns a boolean if a field has been set.
func (o *OrdersPostRequest) HasPreOder() bool {
	if o != nil && !IsNil(o.PreOder) {
		return true
	}

	return false
}

// SetPreOder gets a reference to the given bool and assigns it to the PreOder field.
func (o *OrdersPostRequest) SetPreOder(v bool) {
	o.PreOder = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *OrdersPostRequest) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersPostRequest) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *OrdersPostRequest) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *OrdersPostRequest) SetPrice(v float32) {
	o.Price = &v
}

// GetDeliveryType returns the DeliveryType field value if set, zero value otherwise.
func (o *OrdersPostRequest) GetDeliveryType() float32 {
	if o == nil || IsNil(o.DeliveryType) {
		var ret float32
		return ret
	}
	return *o.DeliveryType
}

// GetDeliveryTypeOk returns a tuple with the DeliveryType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersPostRequest) GetDeliveryTypeOk() (*float32, bool) {
	if o == nil || IsNil(o.DeliveryType) {
		return nil, false
	}
	return o.DeliveryType, true
}

// HasDeliveryType returns a boolean if a field has been set.
func (o *OrdersPostRequest) HasDeliveryType() bool {
	if o != nil && !IsNil(o.DeliveryType) {
		return true
	}

	return false
}

// SetDeliveryType gets a reference to the given float32 and assigns it to the DeliveryType field.
func (o *OrdersPostRequest) SetDeliveryType(v float32) {
	o.DeliveryType = &v
}

// GetDestination returns the Destination field value if set, zero value otherwise.
func (o *OrdersPostRequest) GetDestination() string {
	if o == nil || IsNil(o.Destination) {
		var ret string
		return ret
	}
	return *o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersPostRequest) GetDestinationOk() (*string, bool) {
	if o == nil || IsNil(o.Destination) {
		return nil, false
	}
	return o.Destination, true
}

// HasDestination returns a boolean if a field has been set.
func (o *OrdersPostRequest) HasDestination() bool {
	if o != nil && !IsNil(o.Destination) {
		return true
	}

	return false
}

// SetDestination gets a reference to the given string and assigns it to the Destination field.
func (o *OrdersPostRequest) SetDestination(v string) {
	o.Destination = &v
}

// GetTerminalId returns the TerminalId field value if set, zero value otherwise.
func (o *OrdersPostRequest) GetTerminalId() float32 {
	if o == nil || IsNil(o.TerminalId) {
		var ret float32
		return ret
	}
	return *o.TerminalId
}

// GetTerminalIdOk returns a tuple with the TerminalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersPostRequest) GetTerminalIdOk() (*float32, bool) {
	if o == nil || IsNil(o.TerminalId) {
		return nil, false
	}
	return o.TerminalId, true
}

// HasTerminalId returns a boolean if a field has been set.
func (o *OrdersPostRequest) HasTerminalId() bool {
	if o != nil && !IsNil(o.TerminalId) {
		return true
	}

	return false
}

// SetTerminalId gets a reference to the given float32 and assigns it to the TerminalId field.
func (o *OrdersPostRequest) SetTerminalId(v float32) {
	o.TerminalId = &v
}

// GetTerminalPin returns the TerminalPin field value if set, zero value otherwise.
func (o *OrdersPostRequest) GetTerminalPin() float32 {
	if o == nil || IsNil(o.TerminalPin) {
		var ret float32
		return ret
	}
	return *o.TerminalPin
}

// GetTerminalPinOk returns a tuple with the TerminalPin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersPostRequest) GetTerminalPinOk() (*float32, bool) {
	if o == nil || IsNil(o.TerminalPin) {
		return nil, false
	}
	return o.TerminalPin, true
}

// HasTerminalPin returns a boolean if a field has been set.
func (o *OrdersPostRequest) HasTerminalPin() bool {
	if o != nil && !IsNil(o.TerminalPin) {
		return true
	}

	return false
}

// SetTerminalPin gets a reference to the given float32 and assigns it to the TerminalPin field.
func (o *OrdersPostRequest) SetTerminalPin(v float32) {
	o.TerminalPin = &v
}

// GetReferenceCode returns the ReferenceCode field value if set, zero value otherwise.
func (o *OrdersPostRequest) GetReferenceCode() string {
	if o == nil || IsNil(o.ReferenceCode) {
		var ret string
		return ret
	}
	return *o.ReferenceCode
}

// GetReferenceCodeOk returns a tuple with the ReferenceCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrdersPostRequest) GetReferenceCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ReferenceCode) {
		return nil, false
	}
	return o.ReferenceCode, true
}

// HasReferenceCode returns a boolean if a field has been set.
func (o *OrdersPostRequest) HasReferenceCode() bool {
	if o != nil && !IsNil(o.ReferenceCode) {
		return true
	}

	return false
}

// SetReferenceCode gets a reference to the given string and assigns it to the ReferenceCode field.
func (o *OrdersPostRequest) SetReferenceCode(v string) {
	o.ReferenceCode = &v
}

func (o OrdersPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrdersPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.PreOder) {
		toSerialize["pre_oder"] = o.PreOder
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.DeliveryType) {
		toSerialize["delivery_type"] = o.DeliveryType
	}
	if !IsNil(o.Destination) {
		toSerialize["destination"] = o.Destination
	}
	if !IsNil(o.TerminalId) {
		toSerialize["terminal_id"] = o.TerminalId
	}
	if !IsNil(o.TerminalPin) {
		toSerialize["terminal_pin"] = o.TerminalPin
	}
	if !IsNil(o.ReferenceCode) {
		toSerialize["reference_code"] = o.ReferenceCode
	}
	return toSerialize, nil
}

type NullableOrdersPostRequest struct {
	value *OrdersPostRequest
	isSet bool
}

func (v NullableOrdersPostRequest) Get() *OrdersPostRequest {
	return v.value
}

func (v *NullableOrdersPostRequest) Set(val *OrdersPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrdersPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrdersPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrdersPostRequest(val *OrdersPostRequest) *NullableOrdersPostRequest {
	return &NullableOrdersPostRequest{value: val, isSet: true}
}

func (v NullableOrdersPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrdersPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


